title: Independent Compute Domain
url: https://icdomain.github.io
baseurl: /intelligence
timezone: Etc/UTC
future: true
theme: jekyll-theme-hacker

# forGoogle Search Console
plugins:
  - jekyll-sitemap
